### ISSUE TITLE
Виникнення конфлікту при роботі з файлом

### ISSUE THREAD

**Issue by Tanyuta** [Tanyuta/Binary_studio#1]
КОНФЛИКТ (изменение/удаление): article_1.txt удалено в Updated upstream и изменено в Stashed changes. Версия Stashed changes из article_1.txt оставлена в дереве.

**Comment by volodymyr-kushnir** [comment]
@Tanyuta то що з цим конфліктом? В проблеми немає Assignee і немає лейбла, незрозуміло чи вирішується ця проблема. Загалом як, порядок?

**Comment by Tanyuta** [comment]
Вибачаюся, Володимире, проблему вирiшила але не видаляла issue щоб залишилася в історіі)

**Comment by volodymyr-kushnir** [comment]
Вибачаюся, @Tanyuta, одразу не розгадав ваш хитрий задум.
Окей, бачу тут все в порядку (скоро буде), але все одно порекомендую [**Лайфхаки і підказки**](https://github.com/volodymyr-kushnir/agenda) — раптом щось зацікавить.
