### ISSUE TITLE
Binary studio homework

### ISSUE THREAD

**Issue by Tanyuta** [Tanyuta/Binary_studio#2]
Питання з приводу homework - чи треба мені мерджити всі гілки до master залишаючи два відредагованих артикля, чи залишити дві гілки master + second article для двох артиклів?

**Comment by volodymyr-kushnir** [comment]
@Tanyuta почнем з @. використовуй @volodymyr-kushnir, шоб до адресата доходили повідомлення-нотіфікейшни-сигнали. а то я сюди взагалі чисто випадково попав.
Зліпити все докупи було б дуже файно, але видаляти гілки не обов'язково.

**Comment by volodymyr-kushnir** [comment]
@Tanyuta ну, нема правильного чи неправильного способу створити і вести репозиторій. Це твій репозиторій, ти його ведеш. **Він має бути зручним для користувачів.** А все решта, то вже твій вибір, в нас тут демократія. В контексті самого завдання — якшо дерево виглядає як одна палка `master` — ну то якось це напевно не дуже свідчить про знання гілок і т. д. **В твому випадку всьо в порядку:**

![image](https://cloud.githubusercontent.com/assets/10290626/26287250/63e311e6-3e80-11e7-9035-1cce542a6e89.png)

**Comment by Tanyuta** [comment]
@volodymyr-kushnir , дякую! начебто зробила все!)
